print(8 * 2)
print(12 * 12.50)
print(2025 - 2002)
print(2025 - 1998)
print(2050 - 2021)
print("Em que ano você nasceu?")
nascimento = input()
nascimento = int(nascimento)
print("Em 2025 você terá", 2025 - nascimento, "anos!")
nascimento = int(input("Que ano você nasceu: "))
ano = int(input("Informe o ano que quer saber sua idade: "))
print(f"No ano {ano} você terá {ano - nascimento} anos!")
anos = int(input("Quantos anos você tem?"))
print(f"Se você fosse um cachorro você teria {anos * 7} anos!")
print("o__")
print(" |||| ")
